[package]
authors = ["Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>"]
categories = ["gui", "os::linux-apis", "api-bindings"]
description = "XDG portals wrapper in Rust using zbus"
edition = "2018"
exclude = ["interfaces/*.xml", "ashpd-demo/"]
keywords = ["portal", "flatpak", "xdg", "desktop", "documents"]
license = "MIT"
name = "ashpd"
repository = "https://github.com/bilelmoussaoui/ashpd"
version = "0.2.0-alpha-5"

[features]
default_features = []
feature_gtk3 = ["gdk3x11", "gdk3wayland", "gtk3"]
feature_gtk4 = ["gdk4x11", "gdk4wayland", "gtk4"]
feature_pipewire = ["pw", "libc"]
log = ["tracing"]

[dependencies]
enumflags2 = "0.7"
gdk3x11 = {package = "gdkx11", git = "https://github.com/gtk-rs/gtk3-rs", optional = true}
gdk3wayland = {package = "gdkwayland", git = "https://github.com/gtk-rs/gtk3-rs", optional = true, features = ["v3_22"]}
gtk3 = {package = "gtk", git = "https://github.com/gtk-rs/gtk3-rs", optional = true}

gdk4wayland = {package = "gdk4-wayland", git = "https://github.com/gtk-rs/gtk4-rs", optional = true}
gdk4x11 = {package = "gdk4-x11", git = "https://github.com/gtk-rs/gtk4-rs", optional = true}
gtk4 = {git = "https://github.com/gtk-rs/gtk4-rs", optional = true}

pw = {package= "pipewire", version = "0.4", optional = true}

serde = {version = "1.0", features = ["derive"]}
serde_repr = "0.1"
rand = {version = "0.8", default-features = false}
zbus = "2.0.0-beta.8"
zbus_macros = "2.0.0-beta.8"
zbus_names = "2.0"
zvariant = {version = "3", features = ["enumflags2"], default-features = false}
zvariant_derive = "3"
futures = "0.3"
tracing = {version = "0.1", optional = true}
libc = {version = "0.2.94", optional = true}
